import type {
  Cart,
  CartLine,
  Category,
  CategoryId,
  CollectionId,
  CommerceProvider,
  Money,
  Product,
  PromoSlide,
  Store,
} from "./types";

const categories: Category[] = [
  { id: "fashion", label: "Fashion" },
  { id: "technology", label: "Technology" },
  { id: "home", label: "Home" },
  { id: "beauty", label: "Beauty" },
  { id: "lifestyle", label: "Lifestyle" },
];

const categoryLabels: Record<CategoryId, string> = {
  fashion: "Fashion",
  technology: "Technology",
  home: "Home",
  beauty: "Beauty",
  lifestyle: "Lifestyle",
};

const stores: Store[] = [
  {
    id: "str_aurora",
    slug: "aurora-atelier",
    name: "Aurora Atelier",
    tagline: "Hand-finished lighting for quiet rooms",
    description:
      "A small studio shaping brass and opal glass into lamps that behave like daylight.",
    category: "home",
    categoryLabel: categoryLabels.home,
    location: "Lisbon, PT",
    productCount: 24,
    featured: true,
    cover: {
      gradient: "from-amber-300 via-rose-400 to-fuchsia-600",
      alt: "Aurora Atelier storefront",
    },
    theme: {
      gradient: "from-amber-300 via-rose-400 to-fuchsia-600",
      pattern: "rings",
      accentText: "text-amber-200",
    },
    visualConfig: {
      template: "immersive",
      hero: {
        title: "Light that lives with you",
        description: "Each piece is finished by hand in our Lisbon studio.",
        ctaLabel: "Explore the collection",
      },
      brandStory: {
        title: "The Aurora Story",
        content: "Founded in 2019, Aurora Atelier began with a simple question: what if light could feel like daylight? Our small studio in Lisbon shapes brass and opal glass into lamps that warm a room without dominating it. Every piece is hand-finished, numbered, and built to last.",
      },
      featuredCollectionIds: ["featured"],
      visual: {
        ambientMotion: true,
        density: "spacious",
      },
    },
  },
  {
    id: "str_northbound",
    slug: "northbound-supply",
    name: "Northbound Supply",
    tagline: "Gear built for long, cold distances",
    description:
      "Technical outerwear and packs tested above the tree line before anything ships.",
    category: "fashion",
    categoryLabel: categoryLabels.fashion,
    location: "Tromsø, NO",
    productCount: 41,
    featured: true,
    cover: {
      gradient: "from-sky-300 via-cyan-500 to-blue-700",
      alt: "Northbound Supply storefront",
    },
    theme: {
      gradient: "from-sky-300 via-cyan-500 to-blue-700",
      pattern: "beams",
      accentText: "text-sky-200",
    },
    visualConfig: {
      template: "minimal",
      hero: {
        title: "Tested above the tree line",
        description: "Technical gear for the long way round.",
        ctaLabel: "Shop the collection",
      },
      brandStory: {
        title: "Field-Tested",
        content: "Based in Tromsø, Norway, Northbound Supply designs outerwear and packs that are tested in Arctic conditions before they ever ship. We believe gear should be simple, functional, and built to last.",
      },
      featuredCollectionIds: ["trending"],
      visual: {
        ambientMotion: false,
        density: "compact",
      },
    },
  },
  {
    id: "str_mono",
    slug: "mono-goods",
    name: "Mono Goods",
    tagline: "One object, done properly",
    description:
      "A rotating single-product shop. Each release stays until the next one is ready.",
    category: "lifestyle",
    categoryLabel: categoryLabels.lifestyle,
    location: "Kyoto, JP",
    productCount: 9,
    featured: true,
    cover: {
      gradient: "from-neutral-200 via-neutral-400 to-neutral-700",
      alt: "Mono Goods storefront",
    },
    theme: {
      gradient: "from-neutral-200 via-neutral-400 to-neutral-700",
      pattern: "grid",
      accentText: "text-neutral-200",
    },
    visualConfig: {
      template: "minimal",
      hero: {
        title: "One object at a time",
        description: "Current release: Edition 07 Carafe",
        ctaLabel: "View current edition",
      },
      brandStory: {
        title: "The Mono Philosophy",
        content: "Mono Goods operates on a simple principle: do one thing perfectly. Each release is a single object, designed and produced until the next one is ready. Based in Kyoto, Japan.",
      },
      featuredCollectionIds: ["featured"],
      visual: {
        ambientMotion: false,
        density: "compact",
      },
    },
  },
  {
    id: "str_verdant",
    slug: "verdant-lab",
    name: "Verdant Lab",
    tagline: "Skincare with a short ingredient list",
    description:
      "Formulations developed in-house, batched monthly, printed with full disclosure.",
    category: "beauty",
    categoryLabel: categoryLabels.beauty,
    location: "Copenhagen, DK",
    productCount: 17,
    featured: false,
    cover: {
      gradient: "from-emerald-300 via-teal-500 to-emerald-800",
      alt: "Verdant Lab storefront",
    },
    theme: {
      gradient: "from-emerald-300 via-teal-500 to-emerald-800",
      pattern: "rings",
      accentText: "text-emerald-200",
    },
    visualConfig: {
      template: "editorial",
      hero: {
        title: "Six ingredients. No secrets.",
        description: "Small-batch skincare with full ingredient disclosure.",
        ctaLabel: "Discover the routine",
      },
      brandStory: {
        title: "Transparent Formulation",
        content: "Verdant Lab was founded in Copenhagen with a commitment to transparency. Every formulation is developed in-house, batched monthly, and printed with full ingredient disclosure. No hidden synthetics, no proprietary blends.",
      },
      featuredCollectionIds: ["featured", "trending"],
      visual: {
        ambientMotion: true,
        density: "comfortable",
      },
    },
  },
  {
    id: "str_slowpress",
    slug: "slow-press",
    name: "Slow Press",
    tagline: "Risograph prints in tiny runs",
    description:
      "Independent artists, fifty copies at a time, numbered by hand in the studio.",
    category: "lifestyle",
    categoryLabel: categoryLabels.lifestyle,
    location: "Mexico City, MX",
    productCount: 63,
    featured: false,
    cover: {
      gradient: "from-orange-300 via-red-500 to-purple-700",
      alt: "Slow Press storefront",
    },
    theme: {
      gradient: "from-orange-300 via-red-500 to-purple-700",
      pattern: "grid",
      accentText: "text-orange-200",
    },
    visualConfig: {
      template: "editorial",
      hero: {
        title: "Fifty copies at a time",
        description: "Independent risograph prints, hand-numbered in Mexico City.",
        ctaLabel: "Browse the prints",
      },
      brandStory: {
        title: "Slow by Design",
        content: "Slow Press works with independent artists to produce risograph prints in tiny runs—fifty copies at a time, numbered by hand in our Mexico City studio. Each print is unique, each run is limited.",
      },
      featuredCollectionIds: ["featured"],
      visual: {
        ambientMotion: true,
        density: "comfortable",
      },
    },
  },
  {
    id: "str_hallow",
    slug: "hallow-audio",
    name: "Hallow Audio",
    tagline: "Speakers that disappear into the room",
    description:
      "Cabinetry-first audio, assembled from reclaimed hardwood and open-source drivers.",
    category: "technology",
    categoryLabel: categoryLabels.technology,
    location: "Portland, US",
    productCount: 12,
    featured: false,
    cover: {
      gradient: "from-indigo-300 via-violet-500 to-slate-900",
      alt: "Hallow Audio storefront",
    },
    theme: {
      gradient: "from-indigo-300 via-violet-500 to-slate-900",
      pattern: "beams",
      accentText: "text-indigo-200",
    },
    visualConfig: {
      template: "immersive",
      hero: {
        title: "Audio that disappears",
        description: "Cabinetry-first design with reclaimed hardwood.",
        ctaLabel: "Listen to the difference",
      },
      brandStory: {
        title: "Cabinetry First",
        content: "Hallow Audio is built on a simple idea: the cabinet matters as much as the driver. Based in Portland, Oregon, we assemble speakers from reclaimed hardwood and open-source drivers. No plastic, no hidden electronics.",
      },
      featuredCollectionIds: ["featured"],
      visual: {
        ambientMotion: true,
        density: "spacious",
      },
    },
  },
];

const usd = (amount: number): Money => ({ amount, currency: "USD" });

const products: Product[] = [
  {
    id: "prd_opal_lamp",
    slug: "opal-table-lamp",
    storeId: "str_aurora",
    storeName: "Aurora Atelier",
    name: "Opal Table Lamp",
    description: "Blown opal shade on a solid brass stem with a dimmable warm core.",
    category: "home",
    categoryLabel: categoryLabels.home,
    price: usd(28900),
    image: { gradient: "from-amber-200 to-rose-500", alt: "Opal table lamp" },
    badge: "featured",
    collections: ["featured", "trending"],
    tags: ["lighting", "brass"],
    highlights: ["Hand-blown opal glass", "Solid brass stem", "Dimmable LED core", "Hand-finished in Lisbon"],
    availability: "in-stock",
  },
  {
    id: "prd_halo_sconce",
    slug: "halo-wall-sconce",
    storeId: "str_aurora",
    storeName: "Aurora Atelier",
    name: "Halo Wall Sconce",
    description: "A thin brass ring that throws light up the wall and nowhere else.",
    category: "home",
    categoryLabel: categoryLabels.home,
    price: usd(19500),
    image: { gradient: "from-rose-200 to-fuchsia-600", alt: "Halo wall sconce" },
    collections: ["new-arrivals"],
    badge: "new",
    tags: ["lighting"],
    highlights: ["Solid brass ring", "Upward-facing light", "Minimal installation", "Warm white LED"],
    availability: "in-stock",
  },
  {
    id: "prd_ridge_shell",
    slug: "ridge-shell-jacket",
    storeId: "str_northbound",
    storeName: "Northbound Supply",
    name: "Ridge Shell Jacket",
    description: "Three-layer waterproof shell with taped seams and a helmet-ready hood.",
    category: "fashion",
    categoryLabel: categoryLabels.fashion,
    price: usd(42000),
    image: { gradient: "from-sky-200 to-blue-700", alt: "Ridge shell jacket" },
    badge: "trending",
    collections: ["trending", "featured"],
    tags: ["outerwear", "waterproof"],
    highlights: ["3-layer waterproof membrane", "Fully taped seams", "Helmet-compatible hood", "Pit zips for ventilation"],
    availability: "in-stock",
  },
  {
    id: "prd_fjord_pack",
    slug: "fjord-40l-pack",
    storeId: "str_northbound",
    storeName: "Northbound Supply",
    name: "Fjord 40L Pack",
    description: "Roll-top hauler in recycled sailcloth, balanced for long approaches.",
    category: "fashion",
    categoryLabel: categoryLabels.fashion,
    price: usd(23500),
    image: { gradient: "from-cyan-200 to-blue-800", alt: "Fjord 40 litre pack" },
    collections: ["trending"],
    tags: ["packs"],
    highlights: ["40L capacity", "Recycled sailcloth", "Roll-top closure", "Frame-carry design"],
    availability: "in-stock",
  },
  {
    id: "prd_thermal_layer",
    slug: "thermal-base-layer",
    storeId: "str_northbound",
    storeName: "Northbound Supply",
    name: "Thermal Base Layer",
    description: "Merino blend knitted in one piece, so there is nothing to chafe.",
    category: "fashion",
    categoryLabel: categoryLabels.fashion,
    price: usd(11800),
    image: { gradient: "from-slate-200 to-sky-700", alt: "Thermal base layer" },
    badge: "new",
    collections: ["new-arrivals"],
    tags: ["layers", "merino"],
    highlights: ["Seamless construction", "Merino wool blend", "Moisture-wicking", "Odour-resistant"],
    availability: "low-stock",
  },
  {
    id: "prd_edition_07",
    slug: "edition-07-carafe",
    storeId: "str_mono",
    storeName: "Mono Goods",
    name: "Edition 07 Carafe",
    description: "Borosilicate carafe with a cork stopper. Current and only release.",
    category: "home",
    categoryLabel: categoryLabels.home,
    price: usd(7400),
    image: { gradient: "from-neutral-100 to-neutral-600", alt: "Edition 07 carafe" },
    badge: "featured",
    collections: ["featured"],
    tags: ["kitchen", "limited"],
    highlights: ["Borosilicate glass", "Natural cork stopper", "Hand-finished", "Limited edition"],
    availability: "in-stock",
  },
  {
    id: "prd_desk_tray",
    slug: "folded-desk-tray",
    storeId: "str_mono",
    storeName: "Mono Goods",
    name: "Folded Desk Tray",
    description: "A single sheet of anodised aluminium, folded four times. Nothing else.",
    category: "lifestyle",
    categoryLabel: categoryLabels.lifestyle,
    price: usd(6200),
    image: { gradient: "from-zinc-200 to-zinc-700", alt: "Folded desk tray" },
    collections: ["trending"],
    tags: ["desk"],
    highlights: ["Single sheet construction", "Anodised aluminium", "Four precise folds", "No hardware"],
    availability: "in-stock",
  },
  {
    id: "prd_barrier_serum",
    slug: "barrier-serum",
    storeId: "str_verdant",
    storeName: "Verdant Lab",
    name: "Barrier Serum",
    description: "Six ingredients, batched monthly, dated on the base of every bottle.",
    category: "beauty",
    categoryLabel: categoryLabels.beauty,
    price: usd(5200),
    image: { gradient: "from-emerald-200 to-teal-700", alt: "Barrier serum bottle" },
    badge: "trending",
    collections: ["trending", "featured"],
    tags: ["skincare"],
    highlights: ["Only 6 ingredients", "Monthly batches", "Dated bottles", "Full disclosure"],
    availability: "in-stock",
  },
  {
    id: "prd_clay_cleanser",
    slug: "green-clay-cleanser",
    storeId: "str_verdant",
    storeName: "Verdant Lab",
    name: "Green Clay Cleanser",
    description: "A gentle clay wash that does not strip the skin it is cleaning.",
    category: "beauty",
    categoryLabel: categoryLabels.beauty,
    price: usd(3400),
    image: { gradient: "from-lime-200 to-emerald-700", alt: "Green clay cleanser" },
    collections: ["new-arrivals"],
    badge: "new",
    tags: ["skincare"],
    highlights: ["Green clay base", "Gentle cleansing", "Non-stripping", "pH balanced"],
    availability: "in-stock",
  },
  {
    id: "prd_night_balm",
    slug: "night-repair-balm",
    storeId: "str_verdant",
    storeName: "Verdant Lab",
    name: "Night Repair Balm",
    description: "Thick overnight balm in a refillable glass jar, unscented by design.",
    category: "beauty",
    categoryLabel: categoryLabels.beauty,
    price: usd(4800),
    image: { gradient: "from-teal-200 to-emerald-900", alt: "Night repair balm" },
    collections: ["featured"],
    tags: ["skincare"],
    highlights: ["Overnight repair", "Refillable jar", "Unscented formula", "Glass packaging"],
    availability: "in-stock",
  },
  {
    id: "prd_riso_set",
    slug: "riso-print-set",
    storeId: "str_slowpress",
    storeName: "Slow Press",
    name: "Riso Print Set",
    description: "Three A3 risograph prints, hand-numbered from a run of fifty.",
    category: "lifestyle",
    categoryLabel: categoryLabels.lifestyle,
    price: usd(9800),
    image: { gradient: "from-orange-200 to-purple-700", alt: "Risograph print set" },
    badge: "featured",
    collections: ["featured", "trending"],
    tags: ["print", "limited"],
    highlights: ["3 A3 prints", "Hand-numbered", "Limited to 50", "Risograph printing"],
    availability: "low-stock",
  },
  {
    id: "prd_zine_annual",
    slug: "annual-zine-no-4",
    storeId: "str_slowpress",
    storeName: "Slow Press",
    name: "Annual Zine No. 4",
    description: "Ninety pages of new work from twelve studios, saddle-stitched by hand.",
    category: "lifestyle",
    categoryLabel: categoryLabels.lifestyle,
    price: usd(2600),
    image: { gradient: "from-red-200 to-purple-800", alt: "Annual zine number four" },
    badge: "new",
    collections: ["new-arrivals"],
    tags: ["print"],
    highlights: ["90 pages", "12 studios", "Saddle-stitched", "Hand assembly"],
    availability: "in-stock",
  },
  {
    id: "prd_alcove_speaker",
    slug: "alcove-bookshelf-speaker",
    storeId: "str_hallow",
    storeName: "Hallow Audio",
    name: "Alcove Bookshelf Speaker",
    description: "Reclaimed ash cabinet, paper cone driver, sold as a matched pair.",
    category: "technology",
    categoryLabel: categoryLabels.technology,
    price: usd(64000),
    image: { gradient: "from-indigo-200 to-slate-800", alt: "Alcove bookshelf speaker" },
    badge: "featured",
    collections: ["featured", "trending"],
    tags: ["audio", "pair"],
    highlights: ["Reclaimed ash cabinet", "Paper cone driver", "Matched pair", "Open-source design"],
    availability: "in-stock",
  },
  {
    id: "prd_field_amp",
    slug: "field-amplifier",
    storeId: "str_hallow",
    storeName: "Hallow Audio",
    name: "Field Amplifier",
    description: "A twelve-watt desk amp with one knob and a very short signal path.",
    category: "technology",
    categoryLabel: categoryLabels.technology,
    price: usd(38000),
    image: { gradient: "from-violet-200 to-slate-900", alt: "Field amplifier" },
    collections: ["trending"],
    tags: ["audio"],
    highlights: ["12 watts", "Single knob control", "Short signal path", "Pure Class A"],
    availability: "in-stock",
  },
  {
    id: "prd_thread_turntable",
    slug: "thread-turntable",
    storeId: "str_hallow",
    storeName: "Hallow Audio",
    name: "Thread Turntable",
    description: "Belt-driven deck with a machined platter and no unnecessary lights.",
    category: "technology",
    categoryLabel: categoryLabels.technology,
    price: usd(89000),
    image: { gradient: "from-slate-200 to-indigo-900", alt: "Thread turntable" },
    badge: "new",
    collections: ["new-arrivals", "featured"],
    tags: ["audio"],
    highlights: ["Belt-driven", "Machined platter", "No indicator lights", "33/45 RPM"],
    availability: "low-stock",
  },
  {
    id: "prd_linen_throw",
    slug: "washed-linen-throw",
    storeId: "str_aurora",
    storeName: "Aurora Atelier",
    name: "Washed Linen Throw",
    description: "Heavyweight linen, stonewashed twice, finished with a hand-rolled hem.",
    category: "home",
    categoryLabel: categoryLabels.home,
    price: usd(14500),
    image: { gradient: "from-amber-100 to-rose-400", alt: "Washed linen throw" },
    collections: ["trending"],
    tags: ["textiles"],
    highlights: ["Heavyweight linen", "Double stonewashed", "Hand-rolled hem", "Natural fiber"],
    availability: "in-stock",
  },
  {
    id: "prd_wool_overshirt",
    slug: "wool-overshirt",
    storeId: "str_northbound",
    storeName: "Northbound Supply",
    name: "Wool Overshirt",
    description: "Boiled wool that shrugs off drizzle and reads as a shirt indoors.",
    category: "fashion",
    categoryLabel: categoryLabels.fashion,
    price: usd(19800),
    image: { gradient: "from-blue-200 to-slate-700", alt: "Wool overshirt" },
    badge: "featured",
    collections: ["featured"],
    tags: ["outerwear"],
    highlights: ["Boiled wool", "Water-resistant", "Versatile wear", "Natural insulation"],
    availability: "in-stock",
  },
  {
    id: "prd_travel_kit",
    slug: "everyday-travel-kit",
    storeId: "str_mono",
    storeName: "Mono Goods",
    name: "Everyday Travel Kit",
    description: "A waxed canvas roll sized for exactly what a week away needs.",
    category: "lifestyle",
    categoryLabel: categoryLabels.lifestyle,
    price: usd(8900),
    image: { gradient: "from-stone-200 to-neutral-700", alt: "Everyday travel kit" },
    collections: ["new-arrivals"],
    badge: "new",
    tags: ["travel"],
    highlights: ["Waxed canvas", "Roll design", "Week-sized capacity", "Simple organization"],
    availability: "in-stock",
  },
];

const promoSlides: PromoSlide[] = [
  {
    id: "promo_worlds",
    kicker: "Marketplace",
    title: "Every brand has a world",
    description:
      "Step into storefronts designed by the makers themselves — then take something home.",
    ctaLabel: "Start exploring",
    ctaHref: "/explore",
    theme: {
      gradient: "from-violet-500/40 via-fuchsia-500/25 to-transparent",
      glow: "bg-violet-500/35",
      accentText: "text-violet-200",
    },
    ambient: "aurora",
  },
  {
    id: "promo_northbound",
    kicker: "Vendor spotlight · Northbound Supply",
    title: "Built for the long, cold way round",
    description:
      "The winter range is live: three-layer shells, merino layers and roll-top packs.",
    ctaLabel: "Enter the store",
    ctaHref: "/stores/northbound-supply",
    theme: {
      gradient: "from-sky-400/40 via-cyan-500/25 to-transparent",
      glow: "bg-sky-500/35",
      accentText: "text-sky-200",
    },
    ambient: "beams",
  },
  {
    id: "promo_verdant",
    kicker: "Promotion · Beauty",
    title: "Short ingredient lists, long-standing results",
    description:
      "Verdant Lab batches monthly and dates every bottle. This month's batch is open.",
    ctaLabel: "Shop beauty",
    ctaHref: "/explore",
    theme: {
      gradient: "from-emerald-400/40 via-teal-500/25 to-transparent",
      glow: "bg-emerald-500/35",
      accentText: "text-emerald-200",
    },
    ambient: "orbs",
  },
];

const cartLines: CartLine[] = [
  { id: "line_1", product: products[0], quantity: 1 },
  { id: "line_2", product: products[5], quantity: 2 },
];

function subtotal(lines: CartLine[]): Money {
  return {
    amount: lines.reduce(
      (total, line) => total + line.product.price.amount * line.quantity,
      0,
    ),
    currency: "USD",
  };
}

/**
 * In-memory provider used while no commerce backend is connected. All reads
 * resolve immediately; nothing is persisted and nothing leaves the process.
 */
export const mockProvider: CommerceProvider = {
  name: "mock",
  async getStores() {
    return stores;
  },
  async getFeaturedStores() {
    return stores.filter((store) => store.featured);
  },
  async getStoreBySlug(slug) {
    return stores.find((store) => store.slug === slug) ?? null;
  },
  async getStoreById(storeId: string) {
    return stores.find((store) => store.id === storeId) ?? null;
  },
  async getProducts() {
    return products;
  },
  async getProductsByStore(storeId) {
    return products.filter((product) => product.storeId === storeId);
  },
  async getProductsByCategory(category: CategoryId) {
    return products.filter((product) => product.category === category);
  },
  async getCategories() {
    return categories;
  },
  async getCollection(collection: CollectionId) {
    return products.filter((product) =>
      product.collections.includes(collection),
    );
  },
  async getPromoSlides() {
    return promoSlides;
  },
  async getCart(): Promise<Cart> {
    return {
      id: "cart_mock",
      lines: cartLines,
      subtotal: subtotal(cartLines),
      currency: "USD",
    };
  },
  async getProductBySlug(slug: string): Promise<Product | null> {
    return products.find((product) => product.slug === slug) ?? null;
  },
};
